# This is a basic workflow to help you get started with Actions

name: Deploy application to gh-pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install and Generate
        run: |
          npm install
          npm run generate
        
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: dist
